version: 0.1
environment_variables:
  plaintext:
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:284546856933:devops_demo_post_build"
phases:
  build:
    commands:
      - echo Build started
      - mvn package
  post_build:
    commands:
      - aws sns publish --topic-arn $SNS_TOPIC_ARN --subject 'Build Completed'

artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
