version: 0.1
environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:284546856933:devops_demo_post_build"
phases:
  build:
    commands:
      - aws sns publish --topic-arn $SNS_TOPIC_ARN --subject "Build has started $CODEBUILD_SOURCE_VERSION" --message "Build has started $CODEBUILD_SOURCE_VERSION"
      - mvn package
  post_build:
    commands:
      - aws sns publish --topic-arn $SNS_TOPIC_ARN --subject "Build has completed $CODEBUILD_SOURCE_VERSION" --message "Build has completed $CODEBUILD_SOURCE_VERSION"
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
