apiVersion: v1
kind: ReplicationController
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: IMAGE_TAG
        ports:
        - containerPort: 8080
          name: todo-server
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        - name: MYSQL_HOST
          value: todo.cxotqdb2jx66.us-east-1.rds.amazonaws.com
        - name: MYSQL_DBNAME
          value: todo
        - name: MYSQL_PASSWORD
          value: root1234